const jsondata = [
    {
        "id": "1",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": true,
    },
    {
        "id": "2",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon2",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": false,
    },
    {
        "id": "3",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon3",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": true,
    },
    {
        "id": "4",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon4",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": false,
    },
    {
        "id": "5",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon5",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": true,
    },
    {
        "id": "6",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon6",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": true,
    },
    {
        "id": "7",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon7",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": false,
    },
    {
        "id": "8",
        "icon": "https://www.flaticon.com/premium-icon/icons/svg/163/163784.svg",
        "name": "Jon8",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "Female",
        "time limit": "Quantum Computer Services",
        "performance": 22,
        "live": false,
    }
]

export { jsondata };
